name: Run ri consumer against sdc11073 provider

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        branch: [fix/reference_provider2]
        tls_enable: [true, false]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout sdc11073
        uses: actions/checkout@v3
        with:
          repository: a-kleinf/sdc11073
          ref: ${{ matrix.branch }}
          path: sdc11073_git
      - name: Install sdc11073
        run: |
          python -m pip install -e ./sdc11073_git
      - name: Run test
        run: |
          ./ri_consumer.sh ${{ matrix.tls_enable }}
