name: Run ri consumer against sdc11073 provider

on:
  push:
  schedule:
    # run every morning at 05:00 UTC
    - cron:  '0,40 5,8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout sdc11073 1.1.x
        uses: actions/checkout@v3
        with:
          repository: draegerwerk/sdc11073
          ref: Version_1.1.x
          path: sdc11073_git
      - name: Install sdc11073
        run: |
          python -m pip install -e ./sdc11073_git
      - name: Run test
        run: |
          ./ri_consumer.sh