name: Run sdc11073 consumer against ri provider

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout sdc11073 1.1.x
        uses: actions/checkout@v3
        with:
          repository: draegerwerk/sdc11073
          ref: Version_1.1.x
          path: sdc11073
      - name: Install sdc11073
        run: |
          python -m pip install -e ./sdc11073
      - name: Run test
        run: |
          ./sdc11073_consumer.sh